/* Generated By:JavaCC: Do not edit this line. XMLParserConstants.java */
package converter;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_TAG = 5;
  /** RegularExpression Id. */
  int CLOSE_TAG = 6;
  /** RegularExpression Id. */
  int END_TAG = 7;
  /** RegularExpression Id. */
  int SELF_CLOSE = 8;
  /** RegularExpression Id. */
  int NAME = 9;
  /** RegularExpression Id. */
  int CONTENT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "\"/>\"",
    "<NAME>",
    "<CONTENT>",
  };

}
