/* Generated By:JavaCC: Do not edit this line. XMLParserConstants.java */
package converter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int XML_COMMENT = 5;
  /** RegularExpression Id. */
  int OPEN_TAG = 6;
  /** RegularExpression Id. */
  int CLOSE_TAG = 7;
  /** RegularExpression Id. */
  int END_TAG = 8;
  /** RegularExpression Id. */
  int SELF_CLOSE = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int ATTRIBUTE_VALUE = 12;
  /** RegularExpression Id. */
  int TEXT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<XML_COMMENT>",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "\"/>\"",
    "\"=\"",
    "<NAME>",
    "<ATTRIBUTE_VALUE>",
    "<TEXT>",
  };

}
